version: '3.8'

services:
  swiss-jass-backend:
    build: ./backend
    container_name: swiss-jass-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PLATFORM=raspberry-pi-docker
    volumes:
      - ./backend/prisma:/app/prisma
    command: ["dumb-init", "--", "node", "dist/index.js"]
    networks:
      - swiss-jass-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:alpine
    container_name: swiss-jass-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/certbot:/var/www/certbot
    depends_on:
      swiss-jass-backend:
        condition: service_healthy
    networks:
      - swiss-jass-network

  certbot:
    image: certbot/certbot
    container_name: swiss-jass-certbot
    restart: "no"
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  swiss-jass-network:
    driver: bridge