version: '3.8'

services:
  swiss-jass-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: swiss-jass-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/data/swiss_jass.db
    volumes:
      # Mount database directory for persistence
      - ./data:/data
      # Mount backend directory for development if needed
      - ./backend/prisma:/app/prisma
    networks:
      - swiss-jass-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  swiss-jass-network:
    driver: bridge

volumes:
  swiss-jass-data:
    driver: local