services:
  - type: web
    name: swiss-jass-backend
    env: node
    buildCommand: cd backend && npm install && npm run build && npx prisma generate
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
