name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install web dependencies
        run: |
          cd web
          npm ci

      - name: Run smoke (build bundles + tests + simulate)
        run: |
          cd web
          npm run smoke

      - name: Run production build
        run: |
          cd web
          npm run build

      - name: Deploy to gh-pages branch (git push with fallback)
        env:
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          echo "Prepare gh-pages deploy"
          git --version
          mkdir -p out
          # Allow optional secret PAGES_TOKEN at runtime without evaluating it at workflow compile time
          : ${PAGES_TOKEN:=}
          # Try to fetch existing gh-pages branch using GITHUB_TOKEN; if it doesn't exist create an orphan
          if git ls-remote --exit-code "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git" refs/heads/gh-pages; then
            git clone --branch=gh-pages "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git" out
            cd out
          else
            git clone "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git" out || git clone "https://github.com/${REPO}.git" out
            cd out
            git checkout --orphan gh-pages || true
          fi
          git rm -rf . || true
          cp -r ../web/dist/* ./
          git add -A
          git -c user.name="github-actions[bot]" -c user.email="github-actions[bot]@users.noreply.github.com" commit -m "ci: deploy to gh-pages (${SHA})" || echo "No changes to commit"
          echo "Attempting git push with GITHUB_TOKEN"
          if git push --force "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git" gh-pages; then
            echo "Pushed with GITHUB_TOKEN"
          else
            echo "Push with GITHUB_TOKEN failed."
            if [ -n "${PAGES_TOKEN}" ]; then
              echo "Attempting push with PAGES_TOKEN secret"
              git push --force "https://x-access-token:${PAGES_TOKEN}@github.com/${REPO}.git" gh-pages
            else
              echo "PAGES_TOKEN not set; cannot retry. Please add a personal access token (repo scope) as the secret 'PAGES_TOKEN' in repository settings." >&2
              exit 1
            fi
          fi
