name: Test SSH Connection

on:
  workflow_dispatch:
    inputs:
      test_host:
        description: 'Pi IP address to test'
        required: true
        default: '192.168.1.100'

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ github.event.inputs.test_host }}
          username: ${{ secrets.PI_SSH_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          port: ${{ secrets.PI_SSH_PORT || '22' }}
          debug: true
          script: |
            echo "SSH connection successful!"
            whoami
            pwd
            docker --version
            docker compose version